
servlet:
  port: 8080

spring:
  name: admin-api

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/myscrm_db?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class: com.mysql.cj.jdbc.Driver
    username: root
    password: 8022

mybatis:
  mapper-locations: classpath:mapper/admin/*.xml
  type-aliases-package: com.toceansoft.admin.entity

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql


redis:
  #地址
  host: localhost
  #默认端口
  port: 6379

  database: 0

  password:

  timeout: 10s
  lettuce:
    pool:
      #连接池中最小空闲连接
      min-idle: 0
      #连接池中最大空闲连接
      max-idle: 8
      #连接池中最大数据库连接数
      max-active: 8
      #最大阻塞时间（-代表没有限制）
      max-wait: -1ms